### ISSUE TITLE
Fill more than one input (feature request)

### ISSUE THREAD

**Issue by Prophet-Phoenix** [sblask-webextensions/webextension-simple-form-fill#143]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
Thanks for the addon, it makes my daily documentation easier!

I always tab through the same multiple inputs and insert fills manually.
Would it be possible to fill multiple inputs at once? For example by including some type of command in the template:

`Text for input{TAB}{TAB}Text for other input`

Greetings

**Comment by sblask** [comment]
I am not interested. This is SIMPLE Form Fill.
